"""Pydantic v2 request/response schemas for products."""

from datetime import datetime
from decimal import Decimal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.product_variant import (
    ProductVariantCreate,
    ProductVariantResponse,
)


# ---------------------------------------------------------------------------
# Translation
# ---------------------------------------------------------------------------


class ProductTranslationResponse(BaseModel):
    """A single translation for a product."""

    lang: str = Field(alias="language_code")
    name: str
    description: str | None = None

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)


# ---------------------------------------------------------------------------
# Promotion summary (sale pricing)
# ---------------------------------------------------------------------------


class PromotionSummary(BaseModel):
    """Lightweight promotion info attached to product/cart responses."""

    code: str
    discount_percent: int
    end_date: datetime | None = None

    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------------------------
# Responses
# ---------------------------------------------------------------------------


class ProductResponse(BaseModel):
    """Public product detail returned by API."""

    id: UUID
    slug: str
    price: Decimal
    category_id: int | None = None
    brand: str | None = None
    condition: str | None = None
    condition_rating: int | None = None
    condition_details: dict | None = None
    target_gender: str | None = None
    material: str | None = None
    colors: list[str] | None = None
    trend: str | None = None
    pattern: str | None = None
    season: str | None = None
    cut: list[str] | None = None
    usage: str | None = None
    source_dataset: str | None = None
    image_urls: list[str] = []
    translations: list[ProductTranslationResponse] = []
    variants: list[ProductVariantResponse] = []
    created_at: datetime
    sale_price: Decimal | None = None
    discount_label: str | None = None
    promotion: PromotionSummary | None = None

    model_config = ConfigDict(from_attributes=True)


class ProductListResponse(BaseModel):
    """Paginated product listing."""
    # Will be defined in Phase 2 controllers; schema exists for service usage.
    pass


# ---------------------------------------------------------------------------
# Requests
# ---------------------------------------------------------------------------


class TranslationRequest(BaseModel):
    """A translation payload for create/update requests."""

    lang: str = Field(..., min_length=2, max_length=5, alias="language_code")
    name: str = Field(..., min_length=1, max_length=255)
    description: str | None = Field(None, max_length=2000)

    model_config = ConfigDict(populate_by_name=True)


class CreateProductRequest(BaseModel):
    """Payload for creating a product (admin)."""

    translations: list[TranslationRequest] = Field(
        ..., min_length=1, description="At least one translation required"
    )
    price: Decimal = Field(..., gt=0, max_digits=10, decimal_places=2)
    category_id: int | None = None
    brand: str | None = None
    condition: str | None = None
    condition_rating: int | None = Field(None, ge=1, le=5)
    condition_details: dict | None = None
    target_gender: str | None = None
    material: str | None = None
    colors: list[str] | None = None
    trend: str | None = None
    pattern: str | None = None
    season: str | None = None
    cut: list[str] | None = None
    usage: str | None = None
    source_dataset: str | None = None
    variants: list["ProductVariantCreate"] | None = Field(
        default=None, description="Optional variant list; default variant autogenerated if omitted"
    )


class UpdateProductRequest(BaseModel):
    """Payload for updating a product (admin). All fields optional."""

    translations: list[TranslationRequest] | None = None
    price: Decimal | None = Field(None, gt=0, max_digits=10, decimal_places=2)
    category_id: int | None = None
    brand: str | None = None
    condition: str | None = None
    condition_rating: int | None = Field(None, ge=1, le=5)
    condition_details: dict | None = None
    target_gender: str | None = None
    material: str | None = None
    colors: list[str] | None = None
    trend: str | None = None
    pattern: str | None = None
    season: str | None = None
    cut: list[str] | None = None
    usage: str | None = None
    source_dataset: str | None = None
    image_urls: list[str] | None = None
    variants: list["ProductVariantCreate"] | None = None
